apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}  
spec:
  type: NodePort
  ports:
    - nodePort: 30017
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongodb