kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-standalone
  namespace: {{ .Values.mongo.namespace }}
spec:
  storageClassName: mongodb-standalone
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi