apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-post-service-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-post-service
  ports:
    - nodePort: 30091
      port: 8091
      protocol: TCP
      targetPort: 8091