apiVersion: v1
kind: ConfigMap
metadata:
  name: post-configmap
  namespace: {{ .Values.post.namespace }}
  labels:
    app-start-time: {{ include "app.currentDateTime" . }}
    app-version: {{ include "app.currentVersion" . }}
data:
  MONGODB_SERVICE: "mongodb.{{- .Values.mongo.namespace -}}"
  MONGODB_PORT: "27017"
  MONGODB_DB: "company"