apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-post-service-svc
  namespace: {{ .Values.post.namespace }}
spec:
  ports:
  - port: 8091
    protocol: TCP
    targetPort: 8091
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-post-service