kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongodb-standalone
  namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true