apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-user-service-svc
  namespace: {{ .Values.user.namespace }}
spec:
  ports:
  - port: 8092
    protocol: TCP
    targetPort: 8092
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-user-service