apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-user-service-svc
  namespace: {{ .Values.user.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-user-service
  ports:
    - nodePort: 30092
      port: 8092
      protocol: TCP
      targetPort: 8092