apiVersion: v1
kind: Service
metadata:
  name: post-service-svc
spec:
  type: NodePort
  selector:
    app: post-service
  ports:
    - nodePort: 30091
      port: 8091
      protocol: TCP
      targetPort: 8091