apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-deployment
  labels:
    app: post-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate  
  template:
    metadata:
      labels:
        app: post-service
    spec:
      hostname: post-srv
      containers:
      - name: post-service
        image: epamyauhenbandarenka/kotlin-post-srv:0.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8091
        envFrom:
          - configMapRef:
              name: service-configmap
        env:
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                name: service-secret
                key: DATABASE_USERNAME
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: service-secret
                key: DATABASE_PASSWORD
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8092
          failureThreshold: 1
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8092
          initialDelaySeconds: 60
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8092
          initialDelaySeconds: 50
          failureThreshold: 1
          periodSeconds: 3
