apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - nodePort: 30092
      port: 8092
      protocol: TCP
      targetPort: 8092