apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-service
    spec:
      hostname: user-srv
      containers:
      - name: user-service-container
        image: epamyauhenbandarenka/kotlin-user-srv:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8092
        envFrom:
          - configMapRef:
              name: service-configmap
        env:
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                name: service-secret
                key: DATABASE_USERNAME
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: service-secret
                key: DATABASE_PASSWORD
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8092
          failureThreshold: 1
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8092
          initialDelaySeconds: 40
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8092
          initialDelaySeconds: 30
          failureThreshold: 1
          periodSeconds: 3
