FROM gradle:7.5.0-jdk-alpine AS TEMP_BUILD_IMAGE
ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME
COPY build.gradle.kts settings.gradle.kts $APP_HOME
  
COPY gradle $APP_HOME/gradle
COPY --chown=gradle:gradle . /home/gradle/src
USER root
RUN chown -R gradle /home/gradle/src
    
RUN gradle build || return 0
COPY . .
RUN gradle clean build -x test
    
# actual container
FROM openjdk:17-jdk-slim-buster
ENV ARTIFACT_NAME=post-srv-0.0.3-SNAPSHOT.jar
ENV APP_HOME=/usr/app
    
WORKDIR $APP_HOME
COPY --from=TEMP_BUILD_IMAGE $APP_HOME/build/libs/$ARTIFACT_NAME .
    
ENTRYPOINT exec java -jar ${ARTIFACT_NAME}

