spring:
  data:
    mongodb:
      host: ${MONGODB_SERVICE:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DB:company}
      username: ${MONGODB_USER:root}
      password: ${MONGODB_PASSWORD:rootpassword}
      authentication-database: admin
      auto-index-creation: true
  application:
    name: 'user-srv'
server:
  port: '8092'
api:
  post-srv:
    path: ${POST_PATH:http://localhost:8091/api/v1/posts/}
